### ISSUE TITLE
Results for a crisp gene set do not look correct

### ISSUE THREAD

**Issue by AviMaayan** [dcic/signature-commons#2]
Compare with Enrichr. SigCom returns much less enriched terms which look like a clear error!

**Comment by u8sand** [comment]
The number of enriched terms is because we only currently return the top 500 most significant across all of the enrichr libraries.  Furthermore I believe the significance **would** be different given that were computing the significance from all enrichr libraries (not just within one at a time).  We should definitely take a deeper look at this to ensure that what we are returning is accurate and agrees at least in rank to that which is returned by enrichr.  We can certainly return more results as well, the backend already supports pagination of enriched results.

**Comment by u8sand** [comment]
Fixed in https://github.com/MaayanLab/enrichmentAPI/issues/8
